title: ArchIdeas
description: Enterprise Architecture ideas to bring value for your business!
theme: just-the-docs

url: https://archideas.org

# Set a path/url to a logo that will be displayed instead of the title
logo: "/images/archideas-main-logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/images/archideas-logo.ico"

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link