title: ArchIdeas
description: Enterprise Architecture ideas to bring value for your business!
theme: just-the-docs

url: https://archideas.org

logo: "/images/archideas-main-logo.png"

favicon_ico: "/images/archideas-logo.png"